name: ci

on:
    push:
        tags:
            - '*'

jobs:
    docker:
        runs-on: ubuntu-latest
        environment: Development
        permissions:
            packages: write

        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Extract tag name
              id: get_tag
              run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            - name: Login to Github Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ github.token }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  push: true
                  tags: ghcr.io/${{github.repository_owner}}/urlshortener:${{ steps.get_tag.outputs.VERSION }}
                  secret-envs: |
                      HOST=${{ secrets.HOST }}, PORT=${{ secrets.PORT }}, DB_URL=${{ secrets.DB_URL }}, DB_NAME=${{ secrets.DB_NAME }}, DB_COLLECTION=${{ secrets.DB_COLLECTION }}
